# .github/workflows/firebase-hosting-deploy.yml

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # A branch que irá desencadear o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # Note: O FirebaseExtended/action-hosting-deploy@v0 usa FIREBASE_TOKEN como uma variável de ambiente
          # se não for fornecido um firebaseServiceAccount no 'with'.
          projectId: cookit-83f40 
          channelId: live
        env:
          # É aqui que o seu token de login (obtido via firebase login:ci) deve ser passado.
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }}
