# .github/workflows/firebase-hosting-deploy.yml
# Workflow para deploy automatizado para Firebase Hosting (Custo Zero)

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # A branch que irá desencadear o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código do repositório
      - uses: actions/checkout@v3

      # 2. Ação de Deploy para o Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # O valor deste Secret DEVE ser a Chave JSON da Conta de Serviço
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKIT }}
          projectId: cookit-83f40 # O ID do seu projeto Firebase
          channelId: live # O canal de deploy (produção)
