# .github/workflows/firebase-hosting-deploy.yml

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # A branch que irá desencadear o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Ação para fazer o deploy para o Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }}
          projectId: cookit-83f40 # O ID do seu projeto
          channelId: live # O canal de deploy (produção)
